route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: "discord"

  routes:
    - receiver: "discord"
      match_re:
        severity: critical #|warning
      continue: true

    - receiver: "telegram"
      match_re:
        severity: critical #|warning
      continue: true

receivers:
  - name: 'discord'
    discord_configs:
      - webhook_url: 'WEBHOOK'

  - name: 'telegram'
    telegram_configs:
      - bot_token: 'TOKEN'
        chat_id: ID

